/*
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FederatedIdentityRepresentation {
    #[serde(rename = "identityProvider", skip_serializing_if = "Option::is_none")]
    pub identity_provider: Option<String>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "userName", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl FederatedIdentityRepresentation {
    pub fn new() -> FederatedIdentityRepresentation {
        FederatedIdentityRepresentation {
            identity_provider: None,
            user_id: None,
            user_name: None,
        }
    }
}

