/*
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SocialLinkRepresentation {
    #[serde(rename = "socialProvider", skip_serializing_if = "Option::is_none")]
    pub social_provider: Option<String>,
    #[serde(rename = "socialUserId", skip_serializing_if = "Option::is_none")]
    pub social_user_id: Option<String>,
    #[serde(rename = "socialUsername", skip_serializing_if = "Option::is_none")]
    pub social_username: Option<String>,
}

impl SocialLinkRepresentation {
    pub fn new() -> SocialLinkRepresentation {
        SocialLinkRepresentation {
            social_provider: None,
            social_user_id: None,
            social_username: None,
        }
    }
}
