/*
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpConfig {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<models::UpAttribute>>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::UpGroup>>,
    #[serde(
        rename = "unmanagedAttributePolicy",
        skip_serializing_if = "Option::is_none"
    )]
    pub unmanaged_attribute_policy: Option<models::UnmanagedAttributePolicy>,
}

impl UpConfig {
    pub fn new() -> UpConfig {
        UpConfig {
            attributes: None,
            groups: None,
            unmanaged_attribute_policy: None,
        }
    }
}
