/*
 * Keycloak Admin REST API
 *
 * This is a REST API reference for the Keycloak Admin REST API.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserProfileMetadata {
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<models::UserProfileAttributeMetadata>>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<models::UserProfileAttributeGroupMetadata>>,
}

impl UserProfileMetadata {
    pub fn new() -> UserProfileMetadata {
        UserProfileMetadata {
            attributes: None,
            groups: None,
        }
    }
}
